#!/bin/bash

VERSION="0.1 (clonky monky) Beta"
DB=".gotostore"

CMD=$1
MOD1=$2
MOD2=$3
MOD3=$4
MOD4=$5
MOD5=$6


function usage() {
  echo "Usage: go [OPTION]... [MODIFIERS]... "
  echo "Example: go add pepe '/home/pepe/'"
  echo
  echo "Options:"
  echo "--------"
  echo "  to [key]:                         Go to the configured path."
  echo "  list | ls | l:                    List all available jumps."
  echo "  delete | del | d [key] | all:     Delete the specified key or all keys"
  echo "  rename | r [old-key] [new-key]:   Rename a given key"
  echo "  add | a:                          Add a path to the jump list."
  echo "    Modifiers:"
  echo "    ----------"
  echo "      me:                           Add the current path and set the 'jump' "
  echo "                                    key to the directory name."
  echo "      me as [key]:                  Add the current path and set the 'jump' key."
  echo "      [key] [path]:                 Add the desired path with the key."
  echo "  verion | v:                       Shows the current version."
  echo "  help | v:                         Shows this menu."
}

function setup() {
  if [ ! -f $DB ]; then
    touch "$DB"
  fi
}

function validate() {
  grep -P "[A-Za-z-_0-9]*"
}

function go() {
  local search_key=$1
  local dest=

  dest=$(grep "^$search_key=" $DB | grep -oP "=\K(.*)" )
  echo "Dest -> $dest"
  #cd $dest
}

function list() {
  echo "List of available jumps:"
  cat $DB | sed s/\=\/" => "/ | xargs -I line echo "  " line
}

function add() {
  local entry=""
  case $MOD1 in
    me)
      if [[ $MOD2 == "as" ]]; then
        entry="my-as-key=$MOD3"
      else
        entry="dir-key=$MOD2"
      fi
      ;;
    *)
      entry="$MOD1=$MOD2"
      ;;
  esac

  if [ $entry != "" ]; then
    echo $entry >> $DB
  fi
}

function delete() {
  local del_key=$1
  if [ $del_key == "all" ]: then
    > $DB
  else
    sed -i '/^$del_key=/d' $DB
  fi
}


case $CMD in
  add | a)
    setup
    add
    ;;
  delete | del | d)
    delete $MOD1
    ;;
  rename | r)
    #rename
    ;;
  list | ls | l)
     list
    ;;
  version | v)
    echo "  current ver. $VERSION"
    ;;
  help | h)
    usage 
    ;;
  to)
    go $MOD1
    ;;
  *)
    usage 
    ;;
esac
