#!/usr/bin/env bash

if [ "$1" == "--reps" ]; then
  ###############################################################################
  # Adding repositories

  # SBT Tools
  echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list

  # Spotify
  echo "deb http://repository.spotify.com stable non-free" | sudo tee -a /etc/apt/sources.list
  sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 94558F59

  # Add system tray icons 14.10
  sudo add-apt-repository -y ppa:gurqn/systray-utopic

  # Add Fish Shell
  sudo apt-add-repository -y ppa:fish-shell/release-2

  # Add Oracle JDK
  sudo add-apt-repository -y ppa:webupd8team/java

  # revert System tray icons
  # sudo apt-get install ppa-purge
  # sudo ppa-purge ppa:gurqn/systray-utopic
fi

###############################################################################
# Application Installation
if [ "$1" == "--pkg" ]; then
  sudo apt-get update
  sudo apt-get upgrade

  # Via package manager
  echo "Installing applications via package manager ..."

sudo apt-get -y --force-yes install \
vlc \
spotify-client \
unrar \
rar \
xclip \
vim \
terminator \
fish \
graphviz \
oracle-java7-installer \
oracle-java8-installer \
sbt \
git \
python-setuptools \
python-dev \
build-essential

  ###############################################################################
  # Cleaning up
  echo "Cleaning Up" &&
  sudo apt-get -f install &&
  sudo apt-get autoremove &&
  sudo apt-get -y autoclean &&
  sudo apt-get -y clean


  # Java setup
  echo "Hey! remember to setup your java installation"
  echo ">> sudo update-alternatives --config java"
  echo ">> sudo update-alternatives --config javac"
fi

# Via binaries
if [ "$1" == "--apps" ]; then
  # Google Chrome
  echo "Installing applications via .deb packages ..."
  echo "Installing Google Chrome - 64bit version ..." &&
  wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb &&
  sudo dpkg -i google-chrome-stable_current_amd64.deb &&
  rm -f google-chrome-stable_current_amd64.deb

  # Sublime 3
  echo "Installing Sublime Text 3 ..." &&
  wget http://c758482.r82.cf2.rackcdn.com/sublime-text_build-3083_amd64.deb &&
  sudo dpkg -i sublime-text_build-3083_amd64.deb &&
  rm -f sublime-text_build-3083_amd64.deb
  
  # IntelliJ Idea
  echo "Installing IntelliJ 14.1.3 (141.1010.3) ..." &&
  wget http://download.jetbrains.com/idea/ideaIC-14.1.3.tar.gz &&
  mkdir -p ~/Applications/ &&
  mv ideaIC-14.1.3.tar.gz ~/Applications/ && 
  cd ~/Applications/ &&
  tar -zxvf ideaIC-14.1.3.tar.gz &&
  rm -f ideaIC-14.1.3.tar.gz &&
  cd idea-IC-141.1010.3/bin/ &&
  (echo -e "-Dswing.aatext=true\n-Dsun.java2d.xrender=true" >> idea.vmoptions) &&
  (echo -e "-Dswing.aatext=true\n-Dsun.java2d.xrender=true" >> idea64.vmoptions)
  
fi

if [ "$1" == "--set" ]; then
  # Set custom background
  gsettings set org.gnome.desktop.background picture-options "stretched"
  # gsettings set org.gnome.desktop.background picture-uri "file://"
  
  # Always show menus ubuntu 15.04
  # gsettings set com.canonical.Unity always-show-menus true
  
  # Custom Shortcuts ---------------------------------------------------------------------------------
  
  # Close shortcut ala MacOS X
  gsettings set org.gnome.desktop.wm.keybindings close "['<Alt>q', '<Alt>F4']"
  
  # Play, Next & Stop shortcuts
  gsettings set org.gnome.settings-daemon.plugins.media-keys previous "<Super>F7"
  gsettings set org.gnome.settings-daemon.plugins.media-keys next "<Super>F8"
  gsettings set org.gnome.settings-daemon.plugins.media-keys play "<Super>F9"
  
  # Volume Up, Down & Mute shortcuts
  gsettings set org.gnome.settings-daemon.plugins.media-keys volume-mute "<Super>F10"
  gsettings set org.gnome.settings-daemon.plugins.media-keys volume-down "<Super>F11"
  gsettings set org.gnome.settings-daemon.plugins.media-keys volume-up "<Super>F12"
  
  # Launcher Setup
  # gsettings set com.canonical.Unity.Launcher favorites "['application://ubuntu-software-center.desktop', 'application://nautilus.desktop', 'application://spotify.desktop', 'application://google-chrome.desktop', 'application://sublime_text.desktop', 'application://gvim.desktop', 'unity://running-apps', 'unity://desktop-icon', 'application://terminator.desktop', 'application://unity-control-center.desktop', 'unity://expo-icon', 'unity://devices']"
  
  # Set time format
  gsettings set com.canonical.indicator.datetime time-format "custom"
  gsettings set com.canonical.indicator.datetime custom-time-format "%a %d, %h  %H:%M:%S"
  
  # Notebook power
  gsettings set com.canonical.indicator.power show-percentage true
  
  # Natural Scrolling
  gsettings set org.gnome.settings-daemon.peripherals.touchpad natural-scroll true
  
  # Show real name on panel
  gsettings set com.canonical.indicator.session show-real-name-on-panel true

  # Nautilus Defaults
  gsettings set org.gnome.nautilus.preferences default-folder-viewer "list-view"
  gsettings set org.gnome.nautilus.preferences default-sort-order "type"
  gsettings set org.gnome.nautilus.preferences sort-directories-first true
  
  # Enable auto-save-session
  gsettings set org.gnome.SessionManager auto-save-session true
  
  # Come on, I want it bittersweet!
  sudo bash -c "echo 'vm.swappiness = 10' >> /etc/sysctl.conf"
fi

if [ "$1" == "--set2" ]; then
  mkdir -p $HOME/Applications
  mkdir -p $HOME/Develop/{src,apps,test}
  mkdir -p $HOME/Downloads/{text,media,software,src}
  mkdir -p $HOME/Documents/{docs,taxes,books}
fi


