#!/usr/bin/env bash

###############################################################################
# Adding repositories

# SBT Tools
echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list

# Spotify
echo "deb http://repository.spotify.com stable non-free" | sudo tee -a /etc/apt/sources.list
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 94558F59

# Add system tray icons 14.10
sudo add-apt-repository ppa:gurqn/systray-utopic

# Add Fish Shell
sudo apt-add-repository ppa:fish-shell/release-2

# revert System tray icons
# sudo apt-get install ppa-purge
# sudo ppa-purge ppa:gurqn/systray-utopic

###############################################################################
# Application Installation
sudo apt-get update
sudo apt-get upgrade

# Via package manager
echo "Installing applications via package manager ..."

sudo apt-get install -y \
nautilus-open-terminal \
unrar \
rar \
terminator \
vim \
openjdk-7-jre \
openjdk-7-jdk \
sbt \
git \
xclip \
xchat \
vlc \
spotify-client \
fish

# Via binaries
if [ $1 == "--apps" ]; then
  # Google Chrome
  echo "Installing applications via .deb packages ..."
  echo "Installing Google Chrome - 64bit version ..." &&
  wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb &&
  sudo dpkg -i google-chrome-stable_current_amd64.deb &&
  rm -f google-chrome-stable_current_amd64.deb

  # Sublime 3
  echo "Installing Sublime Text 3 ..." &&
  wget http://c758482.r82.cf2.rackcdn.com/sublime-text_build-3065_amd64.deb &&
  sudo dpkg -i sublime-text_build-3065_amd64.deb &&
  rm -f sublime-text_build-3065_amd64.deb
  
  # IntelliJ Idea
  echo "Installing IntelliJ 14.1.1 (141.178.9) ..." &&
  wget http://download.jetbrains.com/idea/ideaIC-14.1.1.tar.gz &&
  mkdir -p ~/Applications/ &&
  mv ideaIC-14.1.1.tar.gz ~/Applications/ && 
  cd ~/Applications/ &&
  tar -zxvf ideaIC-14.1.1.tar.gz &&
  rm -f ideaIC-14.1.1.tar.gz &&
  cd idea-IC-141.178.9/bin/ &&
  (echo -e "-Dswing.aatext=true\n-Dsun.java2d.xrender=true" >> idea.vmoptions) &&
  (echo -e "-Dswing.aatext=true\n-Dsun.java2d.xrender=true" >> idea64.vmoptions)
  
  # Install Skype
  echo "Installing Skype 4.3 ..." &&
  wget http://download.skype.com/linux/skype-ubuntu-precise_4.3.0.37-1_i386.deb &&
  sudo dpkg -i skype-ubuntu-precise_4.3.0.37-1_i386.deb &&
  rm -f skype-ubuntu-precise_4.3.0.37-1_i386.deb
fi


###############################################################################
# Cleaning up
echo "Cleaning Up" &&
sudo apt-get -f install &&
sudo apt-get autoremove &&
sudo apt-get -y autoclean &&
sudo apt-get -y clean
