[marketplace]
default_skills_installs_purged = true
official_marketplace_auto_installed = true

[[marketplace.sources]]
name = "xAI Official"
git = "https://github.com/xai-org/plugin-marketplace.git"

[models]
default = "grok-4.5"

[cli]
auto_update = true
installer = "npm"w

[ui]
max_thoughts_width = 120
theme = "groknight"
fork_secondary_model = "grok-4.5"
yolo = false
compact_mode = false
